[package]
name = "foo"
version = "0.1.0"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "foo"

[dependencies]
ic-cdk = "0.5.6"
ic-cdk-macros = "0.5.6"
