[package]
name = "foo"
version = "0.1.0"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]
edition = "2018"

[lib]
# rlib due to: https://github.com/rust-lang/cargo/issues/6659
crate-type = ["cdylib", "rlib"]

[dependencies]
ic-cdk = "0.5.6"
ic-cdk-macros = "0.5.6"
